### PR TITLE
Bugfix/map region names

### PR DESCRIPTION
**Pull request by tmelliott**

### CODE REVIEW

**Comment by tmelliott** [comment]
```
* checking dependencies in R code ... WARNING
797'::' or ':::' import not declared from: ‘sf’
```

**Comment by tmelliott** [comment]
@daniel-barnett will make this a hot-fix instead (some other changes on dev that aren't yet ready for release). While fixing above namespace issue, could you also bump version and add heading to NEWS? Cheers - Tom.

**Comment by daniel-barnett** [comment]
Do you mind if:
- we release this now, putting `sf` in Suggests for iNZightPlots
- Afterwards, I shift the code that I added here into the iNZightMaps package function so only that package relies on `sf`

Sorry, I would have done this originally but I kept forgetting I was modifying plots and not maps.

**Comment by tmelliott** [comment]
No worries - it's not on CRAN (yet) so that's fine.

**Pull request merged**
